server: 
  port: 9527
 
spring: 
  application:
    name: kk-springcloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 

# 测试的访问地址：http://localhost:9527/kk/mydept/dept/list

zuul: 
  #ignored-services: kk-springcloud-dept
  prefix: /kk
  ignored-services: "*"
  routes: 
    mydept.serviceId: kk-springcloud-dept
    mydept.path: /mydept/**
    aaa.serviceId: kk-springcloud-zuul-gateway
    aaa.path: /aaa/**
 
info:
  app.name: kk-springcloud
  company.name: www.java3y.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

